name: Build web 2
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node-2
        with:
          node-version-file: ./package.json
          cache-key-prefix: ${{ runner.os }}-node24
          no-save-cache: true

      - name: next cache
        uses: actions/cache@v4
        with:
          path: |
            apps/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-

      - name: build
        env:
          NEXT_TP_BUILD_CACHE : 1
        run: |
          yarn workspace web build
